# Generated by Django 5.0.4 on 2024-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_exam_result_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minutes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
