# Generated by Django 5.0.4 on 2024-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_result_question_remove_result_staff_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
