# Generated by Django 5.0.4 on 2024-04-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_course_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sequence',
        ),
    ]
